version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: blackjack_reactive_mongo
      SPRING_R2DBC_URL: r2dbc:mysql://mysql:3306/blackjack_reactive_mysql
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: 1234
      SPRING_SQL_INIT_MODE: never
    depends_on:
      - mongo
      - mysql
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: blackjack_reactive_mysql
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  mongo-data:
  mysql-data:

networks:
  app-network:
    driver: bridge