spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: blackjack_reactive_mongo

  r2dbc:
    url: r2dbc:mysql://localhost:3306/blackjack_reactive_mysql
    username: root
    password: 1234

  r2dbc.pool:
    enabled: true
    initial-size: 5
    max-size: 20
    max-idle-time: 30m
    validation-query: SELECT 1

  sql:
    init:
      mode: always
      platform: mysql
      continue-on-error: true
      schema-locations: classpath:init.sql

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs